drop table Customer cascade constraints;
drop table Hotel cascade constraints;
drop table Room cascade constraints;
drop table Hotel_Room cascade constraints;
drop table Reservation cascade constraints;
drop table Date_List cascade constraints;
drop table Price_Info cascade constraints;
create table Customer(C_ID varchar2(5),C_Name varchar2(20),Age integer,Gender varchar2(7),Primary key(C_ID));
create table Hotel(Branch_ID integer,H_Name varchar2(20),City varchar2(15),Street_Name varchar2(15),Street_Num integer,State varchar2(2),Phone_Number varchar2(11),Primary key(H_Name, Branch_ID));
create table Room(R_Type varchar2(10),Capacity integer,Primary key(R_Type));
create table Hotel_Room(Branch_ID integer,H_Name varchar2(20), R_Type varchar2(10),Quantity integer,Primary Key (Branch_ID, H_Name, R_Type),Foreign Key (Branch_ID, H_Name) references Hotel(Branch_ID, H_Name) on delete cascade ,Foreign Key (R_Type) references Room(R_Type) on delete cascade);
create table Date_List(Date_month integer, Date_day integer,Date_year integer,Primary key(Date_day, Date_month, Date_year));
create table Price_Info(H_Name varchar2(20),Branch_ID integer,R_Type varchar2(10),Date_month integer,Date_day integer,Date_year integer,Price integer,Num_Avail integer,Primary key (H_Name, Branch_ID, R_Type, Date_month, Date_day, Date_year),Foreign key (H_Name, Branch_ID) references Hotel(H_Name, Branch_ID) on delete cascade ,Foreign key (R_Type) references Room(R_Type) on delete cascade ,Foreign key (Date_month, Date_day, Date_year) references Date_List(Date_month, Date_day, Date_year) on delete cascade);
create table Reservation(Res_Num varchar2(7),C_ID varchar2(5),Party_Size integer, Total integer,month_in integer,day_in integer,year_in integer,month_out integer,day_out integer,year_out integer,H_Name varchar2(20),Branch_ID integer,R_Type varchar2(10), Primary key (Res_Num),Foreign key (C_ID) references Customer(C_ID) on delete cascade ,Foreign key (month_in, day_in, year_in) references Date_List(Date_month, Date_day, Date_year) on delete cascade,Foreign key (month_out, day_out, year_out) references Date_List(Date_month, Date_day, Date_year) on delete cascade,Foreign key (H_Name, Branch_ID) references Hotel(H_Name, Branch_ID) on delete cascade,Foreign key (R_Type) references Room(R_Type) on delete cascade);
